# User config
author: "Wanda Felsenhardt"
tagline: "Design+Illustration"
description: "Hello! My name's Wanda. I'm interested in design that benefits people and communicates important issues clearly."
email: "wandafelsen@gmail.com"
linkedin: "https://linkedin.com/in/wanda-f-290960148/"
resume: "https://drive.google.com/open?id=1synRWt0mvST5o1LFhwB4Aw2sEBYrov5x"
instagram: "https://www.instagram.com/amandineflint/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
