# User config
author: "Wanda Felsenhardt"
tagline: "Design+Illustration"
description: "Hello! My name's Wanda. I'm interested in design that benefits people and communicates important issues clearly."
email: "wandafelsen@gmail.com"
linkedin: "https://linkedin.com/in/wanda-f-290960148/"
twitter: "https://twitter.com/Wandafels"
resume: "https://drive.google.com/file/d/1iTe2f5IRcGlL3isXz3J7l18nZvFbaGAf/view?usp=sharing"
instagram: "https://www.instagram.com/amandineflint/"

# Site config
baseurl: "/Portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
